export const ENV_CONSTANTS = {
  TYPEORM_HOST: 'localhost',
  TYPEORM_PORT: 1433,
  TYPEORM_USERNAME: 'sa',
  TYPEORM_PASSWORD: '123456',
  TYPEORM_DATABASE: 'travel',
  TYPEORM_ENTITIES: 'dist/**/*.entity{.ts,.js}',
  TYPEORM_SYNCHRONIZE: true,
  TYPEORM_ENCRYPT: true,
  TYPEORM_ENABLEARITHABORT: true,
  TYPEORM_TRUSTSERVERCERTIFICATE: true,

  APP_PORT: 8081,
};
